morph-data/morph

core/morph/task/utils/run_backend/execution.py
Fix: use local profile connection on local.
=> fix: run sql with connection on local

pyproject.toml
Update version in pyproject.toml
none
publish to testpypi
=> Update pyproject.toml version to v0.0.3 for release

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/config.yml, CONTRIBUTING.md, README.md
Added a contribution guide in `contributing.md`.
none
- Viewed the rendered page on github.
- check if all links in documents work correctly
none
=> add contribution guide

core/morph/include/starter_template/.gitignore
- add node_modules to .gitignore for morph new command
=> chore: add node_modules to .gitignore for morph new command

core/morph/include/starter_template/package.json
- Add an npm run build command to build morph's frontend project.
=> feat: add `npm run build` command

README.md, core/morph/api/service.py, core/morph/api/utils.py, core/morph/cli/params.py, core/morph/constants.py, core/morph/task/utils/run_backend/inspection.py, core/morph/task/utils/run_backend/state.py
- remove unused cli params
- remove vg.json
=> fix: unused cli params & file extensions

core/morph/frontend/template/package.json, core/morph/frontend/template/src/custom-mdx-components.tsx
- update @use-morph/components to 0.1.0-beta.5
=> chore: bump @use-morph/components

core/morph/task/deploy.py
* fixed configure environment variables before running deployment
* added api secret key validation
=> Configure environment variables before deployment

core/morph/task/utils/connections/snowflake/api.py
fix: snowflake account identifier formatter
=> Format snowflake account identifier

core/morph/task/utils/connection.py, core/morph/task/utils/connections/database/postgres.py
add timezone params to postgresql connection
=> Add timezone to postgresql connection

core/morph/frontend/template/src/admin/datapipeline/ResourceDetail.tsx
- Hide Scheduled Jobs UI in Admin Page
=> refactor: remove sheduled jobs UI

core/morph/frontend/template/package.json, core/morph/frontend/template/src/custom-mdx-components.tsx, core/morph/frontend/template/src/main.tsx, core/morph/frontend/template/src/page-skeleton.tsx, core/morph/frontend/template/vite.config.ts
- Remove @use-morph/components and install @morph-data/components instead
- defineState API added
- I confirmed locally that the state defined with defineState is functioning reactively.
=> feat: add defineState API

core/morph/frontend/template/tsconfig.app.json
- loosen tsconfig options for linting to pass frontend build
=> fix: loosen tsconfig.json

pyproject.toml
=> update version v0.1.1

core/morph/frontend/template/tsconfig.app.json, pyproject.toml
Merge release/v0.1.1 into develop
=> Merge release/v0.1.1 into develop

core/morph/api/cloud/client.py, core/morph/task/deploy.py
remove project id validation from morph config command
=> fix: remove project id validation for morph config

core/morph/task/utils/run_backend/output.py
fix: error handling for parquet transform
=> Bug fix transform parquet output error handling

core/morph/api/cloud/client.py, core/morph/cli/main.py, core/morph/cli/params.py, core/morph/task/context.py
add morph context command
executed command and checked if user information successfully printed and saved into specific file path.
=> Add new feature morph context command

core/morph/api/cloud/types.py, core/morph/task/context.py
fix: UserInfo to snake case at morph context command
=> UserInfo to snake case at morph context command

core/morph_lib/stream.py
- add stream_chat for simple usage
none
test behavior with <LLM/> in local environment
=> add stream_chat for simple usage

core/morph/api/cloud/client.py
fix: morph config command without morph_project.yml
checked whether if morph config command works without morph_project.yml
=> Fixed to work even if morph_project.yml is not present when morph config command is executed

core/morph/include/starter_template/.mock_user_context.json
add mock_user_context.json to stater_template
none
- run morph new locally
=> add mock_user_context.json to stater_template

core/morph/api/utils.py
fix: convert NaN and NaT to None in case of running python files for morph serve
checked whether if null values are returned as result
=> Fix convert invalid dataframe type

core/morph/task/api.py, core/morph/task/run.py
fix: load profile from morph_project.yml instead of "default" value
checked to set specific profile and load it
=> Load project profile instead of default

pyproject.toml
=> update version as v0.1.3

core/morph/task/new.py, pyproject.toml
Merge release/v0.1.4 into main
=> Merge release/v0.1.4 into main

pyproject.toml
=> Update version as v0.1.5

core/morph/frontend/template/package.json
Update components package to v0.1.5 with Github flavor markdown parser
=> Update components package to v0.1.5

pyproject.toml
=> update version as v0.1.6

pyproject.toml
=> update version as v0.1.7

pyproject.toml
=> update version as v0.1.8

core/morph/include/Dockerfile, core/morph/include/starter_template/.dockerignore
- update starter template using new dockerfile
=> update starter template using new dockerfile

README.md
replace demo image with gif
none
Looking to github page
=> replace demo image with gif

core/morph/frontend/template/package.json
=> bump @morph-data/components

core/morph/include/starter_template/src/sql/example_data.sql, core/morph/task/utils/connections/connector.py
=> fix duckdb execution when running morph serve

core/morph/api/app.py, core/morph/api/error.py, core/morph/task/api.py, core/morph/task/server.py, core/morph/task/utils/run_backend/errors.py, core/morph/task/utils/run_backend/inspection.py, core/morph_lib/api.py, core/morph_lib/database.py, poetry.lock, pyproject.toml
- print detailed log every time server restarts
test launching server locally
=> print detailed log every time server restarts

core/morph/task/utils/run_backend/decorators.py
- remove title from @morph.func params
none
tested it locally
=> remove title from @morph.func params

core/morph/task/utils/run_backend/output.py
fix: run stream response in case of async function
=> Fix run stream and write response in case of async function

core/morph/task/new.py
- add uv as package manager
none
=> add uv as package manager

core/morph/api/app.py, core/morph/api/service.py, core/morph/cli/main.py, core/morph/config/project.py, core/morph/include/Dockerfile, core/morph/include/starter_template/morph_project.yml, core/morph/task/compile.py, core/morph/task/deploy.py, core/morph/task/resource.py, core/morph/task/run.py, core/morph/task/utils/run_backend/cache.py, core/morph/task/utils/run_backend/decorators.py, core/morph/task/utils/run_backend/execution.py, core/morph/task/utils/run_backend/inspection.py, core/morph/task/utils/run_backend/state.py, core/morph_lib/function.py
- remove meta.json
- remove result_ttl
=> remove meta.json & result_ttl

core/morph/task/deploy.py, core/morph/task/new.py
fix: morph new & deploy command for uv
=> Fix uv package manager

core/morph/task/run.py, core/morph/task/utils/run_backend/execution.py, core/morph/task/utils/run_backend/state.py
fix: set correct value in case of updating meta object
=> Fix update meta object value

core/morph/frontend/template/package.json
Update frontend package to 0.2.0
=> Update frontend package to 0.2.0

core/morph/include/Dockerfile
Fix dockerfile comment
Made starter template runnable without any package installation.
=> Fix dockerfile comment

pyproject.toml
=> update version as v0.2.0

core/morph/api/service.py
fix: cache path for upload file api
=> Fix upload file endpoint cache path

core/morph/api/cloud/client.py, core/morph/config/project.py, core/morph/task/deploy.py, core/morph/task/new.py
feature: added deploy and build setting to morph_project.yml
=> Added deploy and build setting to morph_project.yml

core/morph/include/starter_template/package.json, core/morph/include/starter_template/src/pages/_app.tsx, core/morph/task/api.py
- Bump @morph-data/frontend and update starter template
=> chore: update @morph-data/frontend

pyproject.toml
=> update version as v0.3.0rc1

core/morph/task/deploy.py, core/morph/task/utils/load_dockerfile.py
- Change the way to get dockerfile and dockerignore from hard coding to calling api
=> Get dockerfile by calling api

core/morph/config/project.py
=> fix initial morph_project.yml

core/morph/config/project.py, core/morph/task/deploy.py, core/morph/task/utils/load_dockerfile.py
=> change dockerfile api call

pyproject.toml
=> Issue v0.3.0rc2

core/morph/include/starter_template/src/pages/404.mdx, core/morph/include/starter_template/src/pages/404.tsx
=> fix: 404.mdx → 404.tsx

core/morph/task/utils/load_dockerfile.py, pyproject.toml
=> update version as v0.3.0rc3

pyproject.toml
=> update version as v0.3.0

core/morph/api/cloud/client.py
=> Fix api base url

pyproject.toml
=> update version as v0.3.1
